CREATE DATABASE atomurl;

\c atomurl;
CREATE TABLE  atomurls(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR,
    long_url VARCHAR,
    alias VARCHAR
);

CREATE DATABASE atomurl_test WITH TEMPLATE atomurl;